name: Feature Request
description: Suggest a feature or enhancement
title: "feat(auth): write a suitable title all in lowercase"
labels: ["feat"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Describe your changes in detail.

  - type: textarea
    id: related_issue
    attributes:
      label: Related Issue (Link to issue ticket)
      placeholder: Link to the issue related to this PR, if any.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Context
      placeholder: Why is this change required? What problem does it solve?

  - type: textarea
    id: testing
    attributes:
      label: How Has This Been Tested?
      placeholder: Describe in detail how you tested your changes.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if appropriate — Postman, etc.)
      placeholder: Add screenshots or related material.

  - type: checkboxes
    id: types_of_changes
    attributes:
      label: Types of changes
      options:
        - label: Bug fix (non-breaking change which fixes an issue)
        - label: New feature (non-breaking change which adds functionality)
        - label: Breaking change (fix or feature that would cause existing functionality to change)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: My code follows the code style of this project.
        - label: My change requires a change to the documentation.
        - label: I have updated the documentation accordingly.
        - label: I have read the **CONTRIBUTING** document.
        - label: I have added tests to cover my changes.
        - label: All new and existing tests passed.
