"""Add profile_setup + child_profile tables

Revision ID: 875d524bf108
Revises: 313afcd4440e
Create Date: 2025-11-22 02:05:28.054845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875d524bf108'
down_revision: Union[str, Sequence[str], None] = '313afcd4440e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_setup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mom_status', sa.Enum('pregnant', 'new_mom', 'toddler_mom', 'mixed', name='momstatusenum'), nullable=False),
    sa.Column('goals', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('partner', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_setup_user_id'), 'profile_setup', ['user_id'], unique=True)
    op.create_table('child_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_setup_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_setup_id'], ['profile_setup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_profile_profile_setup_id'), 'child_profile', ['profile_setup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_child_profile_profile_setup_id'), table_name='child_profile')
    op.drop_table('child_profile')
    op.drop_index(op.f('ix_profile_setup_user_id'), table_name='profile_setup')
    op.drop_table('profile_setup')
    # ### end Alembic commands ###
