"""update datetime fields to use timezone aware UTC

Revision ID: 9115429a5f2a
Revises: c3698ef51d6b
Create Date: 2025-11-17 22:36:08.059221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9115429a5f2a'
down_revision: Union[str, Sequence[str], None] = 'c3698ef51d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
